### ISSUE TITLE
Failed to install on linux 

### ISSUE THREAD

**Issue by DnickC** [JanCBrammer/OpenHRV#36]
I would like to give this project a try but I can't get in installed. What I done so far:
- create an environment using miniconda
- install git and clone the project
at this point running python -m openhrv.app results in output:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/dnickc/miniconda3/envs/openHRV/OpenHRV/openhrv/__init__.py", line 4, in <module>
    __version__ = version("OpenHRV")  # read version from pyproject.toml
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for OpenHRV
```
I then installed following dependencies, manually (is there a better way?) 
- yside6=6.5.2, black, mypy

Output after running python -m openhrv.app now reads:
```
Traceback (most recent call last):
  File "/home/dnickc/miniconda3/envs/openHRV/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/dnickc/miniconda3/envs/openHRV/OpenHRV/openhrv/__init__.py", line 4, in <module>
    __version__ = version("OpenHRV")  # read version from pyproject.toml
                  ^^^^^^^^^^^^^^^^^^
  File "/home/dnickc/miniconda3/envs/openHRV/lib/python3.11/importlib/metadata/__init__.py", line 1008, in version
    return distribution(distribution_name).version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dnickc/miniconda3/envs/openHRV/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dnickc/miniconda3/envs/openHRV/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for OpenHRV
```

I don't know how to continue from here, I am very new to the python and virtual env, so maybe missing something obvious. Any help is welcome!

**Comment by JanCBrammer** [comment]
Thanks for reporting this @DnickC!

It seems that I forgot to update the documentation after I've introduced d997e27076f1b65c3c981b9380375bfd9174a7ec.

You need to run `pip install .` (the `.` tells pip that we want a local install, i.e., not fetching anything from PyPI; see https://pip.pypa.io/en/stable/topics/local-project-installs).
Otherwise, `python -m openhrv.app` fails with the traceback you've posted (thanks for including the tracebacks, they were very helpful in diagnosing this).

Can you try running `pip install .` before running `python -m openhrv.app`? I'll update the docs accordingly.

**Comment by JanCBrammer** [comment]
> I then installed following dependencies, manually (is there a better way?)

`pip install .` will also install the dependencies for you btw.

**Comment by DnickC** [comment]
Thank you for the feedback.
I guess I'm still doing something wrong..
At first I tried the pip command in the same environment as before, this resulted in the following output:
```
pip install .
WARNING: Skipping /home/dnickc/miniconda3/envs/openHRV/lib/python3.11/site-packages/PySide6-6.5.2.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /home/dnickc/miniconda3/envs/openHRV/lib/python3.11/site-packages/shiboken6-6.5.2.dist-info due to invalid metadata entry 'name'
Processing /home/dnickc/miniconda3/envs/openHRV/OpenHRV
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: OpenHRV
  Building wheel for OpenHRV (pyproject.toml) ... done
  Created wheel for OpenHRV: filename=OpenHRV-0.2.0-py3-none-any.whl size=46112 sha256=19cb0dc61fbb39cdf986d194494aa653c215422f0c5bedca33854236399e8d18
  Stored in directory: /tmp/pip-ephem-wheel-cache-965htc0g/wheels/5f/f7/c0/591db2d2b35a38c4a27657e4a14b01ec44cd7c066be24265bb
Successfully built OpenHRV
WARNING: Skipping /home/dnickc/miniconda3/envs/openHRV/lib/python3.11/site-packages/PySide6-6.5.2.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /home/dnickc/miniconda3/envs/openHRV/lib/python3.11/site-packages/shiboken6-6.5.2.dist-info due to invalid metadata entry 'name'
Installing collected packages: OpenHRV
WARNING: Skipping /home/dnickc/miniconda3/envs/openHRV/lib/python3.11/site-packages/PySide6-6.5.2.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /home/dnickc/miniconda3/envs/openHRV/lib/python3.11/site-packages/shiboken6-6.5.2.dist-info due to invalid metadata entry 'name'
Successfully installed OpenHRV-0.2.0


python -m openhrv.app
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/dnickc/miniconda3/envs/openHRV/OpenHRV/openhrv/app.py", line 3, in <module>
    from openhrv.view import View
  File "/home/dnickc/miniconda3/envs/openHRV/OpenHRV/openhrv/view.py", line 21, in <module>
    from PySide6.QtCharts import QChartView, QChart, QSplineSeries, QValueAxis, QAreaSeries
ImportError: libQt6Charts.so.6: cannot open shared object file: No such file or directory

```

After this failed I tried again from scratch in a newly created environment, here pip fails to install some dependencies:

```
pip install .
Processing /home/dnickc/miniconda3/envs/openHRV/OpenHRV
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of openhrv to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 6.0.0 Requires-Python >=3.6, <3.10; 6.0.0a1.dev1606911628 Requires-Python >=3.6, <3.10; 6.0.1 Requires-Python >=3.6, <3.10; 6.0.2 Requires-Python >=3.6, <3.10; 6.0.3 Requires-Python >=3.6, <3.10; 6.0.4 Requires-Python >=3.6, <3.10; 6.1.0 Requires-Python >=3.6, <3.10; 6.1.1 Requires-Python >=3.6, <3.10; 6.1.2 Requires-Python >=3.6, <3.10; 6.1.3 Requires-Python >=3.6, <3.10; 6.2.0 Requires-Python >=3.6, <3.11; 6.2.1 Requires-Python >=3.6, <3.11; 6.2.2 Requires-Python >=3.6, <3.11; 6.2.2.1 Requires-Python >=3.6, <3.11; 6.2.3 Requires-Python >=3.6, <3.11; 6.2.4 Requires-Python >=3.6, <3.11; 6.3.0 Requires-Python <3.11,>=3.6; 6.3.1 Requires-Python <3.11,>=3.6; 6.3.2 Requires-Python <3.11,>=3.6; 6.4.0 Requires-Python <3.11,>=3.6; 6.4.0.1 Requires-Python <3.12,>=3.7; 6.4.1 Requires-Python <3.12,>=3.7; 6.4.2 Requires-Python <3.12,>=3.7; 6.4.3 Requires-Python <3.12,>=3.7; 6.5.0 Requires-Python <3.12,>=3.7; 6.5.1 Requires-Python <3.12,>=3.7; 6.5.1.1 Requires-Python <3.12,>=3.7; 6.5.2 Requires-Python <3.12,>=3.7; 6.5.3 Requires-Python <3.12,>=3.7
ERROR: Could not find a version that satisfies the requirement PySide6==6.5.2 (from openhrv) (from versions: 6.6.0, 6.6.1, 6.6.2)
ERROR: No matching distribution found for PySide6==6.5.2
```

Hope I explained this clearly.

**Comment by JanCBrammer** [comment]
Good to hear! Thanks for your feedback, it prompted me to improve the docs.
I'm closing this issue, please don't hesitate to open another one should you run into trouble.
